### ISSUE TITLE
Installation of latest basler drivers is not handled on robots

### ISSUE THREAD

**Issue by texhnolyze** [bit-bots/bitbots_main#214]
# Summary
With the new `make_basler.sh` script we now have to manually copy and execute the script to
install the latest basler deb packages.

## Expected behavior
To prevent confusion and version drift I would expect the latest balser package to be installed after a robot setup.

## Current behavior
The script is not executed on the robot and if we have updated the used pylon driver version in the meantime, it will not be updated unless done manually.

## Possible Solution
It would be a lot easier to include the execution of the script in a remote shell, with our `deploy_robots.py` script.
Another alternative could also be the installation of the pylon drivers via `ansible`, during the setup of ros.

**Comment by jaagut** [comment]
I would prefer the installation via ansible.

**Comment by jaagut** [comment]
This now gets handled by the deploy tool

**Comment by jaagut** [comment]
Resolved with #223
