### ISSUE TITLE
Pre-generate the .wav files from mimic

### ISSUE THREAD

**Issue by jaagut** [bit-bots/bitbots_main#228]
Instead of dynamically calling mimic, we could pre-generate the .wav files and just play them on time.
I would like `<robot_name> <robot_id> is still on!`: `Amy One is still on!` instead of `NUC One is still on!`

_Originally posted by @jaagut in https://github.com/bit-bots/humanoid_league_misc/issues/129#issuecomment-1497200076_

**Comment by Flova** [comment]
Closing in favor of #353
