### ISSUE TITLE
Automated servo torque testing

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_main#243]
Test max torque of each servo to see at which position it should be installed and save data to compare again after one year. Also use it to calibrate servo internal force meassurement.
For this build a test setup with a strain gauge that measures how much the servo moves and fix the motorhorn.
Then have a script running that detects the id of the connected servo, gives commands and reads the strain gauge with one of our foot pressure boards.

**Comment by Flova** [comment]
I think we decided against testing all servos and opt for testing a few to get a better simulation model

**Comment by Flova** [comment]
see https://github.com/Rhoban/bam
