### ISSUE TITLE
Buttons: what is the intended workflow for `in_game` parameter?

### ISSUE THREAD

**Issue by jaagut** [bit-bots/bitbots_main#277]
Regarding the bitbots_button node: what is the intended workflow for `in_game` parameter?

Our (WIP) documentations states, that we should long press the green button to reset the foot pressure sensors.
(I believe long press has been removed? Please provide some documentation in the docs which button does what in which state)
However, this seems to only work if the `in_game` parameter is set to false. By default, it is true.
This means, the reset never gets called.
There should be a workflow that intelligently changes the value of this parameter (e.g. if connected to a game controller and game is running?).

Please point me to some documentation that describes this behavior, if it already exists. Else, we should discuss how to move forward.

**Comment by Flova** [comment]
Done in #350
