### ISSUE TITLE
Dynup Slow Shutdown

### ISSUE THREAD

**Issue by SammyRamone** [bit-bots/bitbots_main#296]
Let Dynup simple action server not directly shut down so we can use it to make the robot sit down. Currently the HCM is still using the sitdown animation in that case, because the DynUp server will directly be shut down. It looks like this can not be changed easily, since the execution loop of the simple action server directly shuts down.

## Describe alternatives you've considered
We could keep using the sitdown animation like now.

**Comment by Flova** [comment]
We don't plan to sit down
