### ISSUE TITLE
Dynup: First walkready pose is broken

### ISSUE THREAD

**Issue by 16stelter** [bit-bots/bitbots_main#309]
When going into walkready after the power has been turned on, the IK solution for the walkready pose is bad, sometimes leading to the feet interlocking or joints colliding. This potentially causes damage to the robot. This seems more likely to happen when joints are outside of the accepted range, but this needs to be further evaluated.

## Expected behavior

Directly move to the walkready pose.

## Current behavior

Move to walkready through weird paths.

## Steps to Reproduce

1. Turn off motor power and stop all software
2. Turn on motor power
3. Start motion_standalone.launch
...

## Context (Environment)

- [ ] RViz
- [ ] Simulator
- [ ] Robot
- [ ] Local

**Comment by timonegk** [comment]
Partially fixed by #407
