### ISSUE TITLE
HCM: Walkready sometimes not executed

### ISSUE THREAD

**Issue by 16stelter** [bit-bots/bitbots_main#310]
When starting the motion, sometimes the robot does not go to walkready, and does not accept any other goals. This can be temporarily fixed by disabling and reenabling motor power, then restarting the node. This does not seem to be depending on the robot pose. Console also constantly prints motor power is off, which might be related, but this is also printed when the motion works.

## Expected behavior

Always go to walkready when starting the motion.

## Current behavior

Sometimes go to walkready when starting the motion.

## Steps to Reproduce

1. Start motion_standalone
2. Repeat 1 until issue appears
3. Turn off/on motor power
4. Start motion_standalone

## Context (Environment)

- [ ] RViz
- [ ] Simulator
- [ ] Robot
- [ ] Local

**Comment by Flova** [comment]
This has been fixed
