### ISSUE TITLE
Stabilisation during walking

### ISSUE THREAD

**Issue by texhnolyze** [bit-bots/bitbots_main#314]
If it is needed, because of backlash issues in the legs we want to do active stabilization during walking.

Wait for results of: https://github.com/bit-bots/bitbots_hardware/issues/42

**Comment by texhnolyze** [comment]
We should take a look at the following PR: https://github.com/bit-bots/bitbots_motion/pull/387
and potentially take it as a basis for this issue.

**Comment by jgueldenstein** [comment]
@Flova would you say that this is solved "enough" by the imu phase reset? What other stabilization techniques did you want to try ?

**Comment by Flova** [comment]
We currently do the phase reset and have a pid controller moving the trunk offset (translation) iirc. That works pretty well.
