### ISSUE TITLE
Fix our kick motion

### ISSUE THREAD

**Issue by texhnolyze** [bit-bots/bitbots_main#316]
If we end up having time before the RoboCup we want to fix our current kick.
While it works ok in simulation in reality we fall over and often do not hit the ball.
Ideas to improve are:
- change assumptions about splines (order, number, etc.)
- potentially reduce the complexity of the current approach while also increasing the speed of the full motion
- improve active stabilisation
- improve current parameters

**Comment by timonegk** [comment]
We don't want to use the dynamic kick in the near future
