### ISSUE TITLE
Walking: tune walk kicks

### ISSUE THREAD

**Issue by jaagut** [bit-bots/bitbots_main#320]
## Is your feature request related to a problem? Please describe.
We cannot kick at the moment.

## Describe the solution you'd like
We should use the walk-kick feature instead.
Don't do this by moving the foot further and back again after touching the ball, but rather setting the foot down after accelerated step-movement.
Side-kicks are also possible by rotating the foot. Afterward, we may need to revert the foot rotation.
Look at Hulks or other SPL teams for details.

**Comment by 00lake00** [comment]
### Meeting with Flo and Jan

* lower frequency of step and phase reset would be helpful in keeping balance @Flova 
* kick_phase parameter should be 0.4/0.5
* velocity nice for longer kick
* roll for longer kick?
* longer foot down length for kick than normal walking? --> balance issue for big step after kick but with small difference nice

*TODO*
* parameter tuning on real roboter
* plotyuggler show joint position error

**Comment by timonegk** [comment]
Walk kick should be adapted to the current kick animation
