### ISSUE TITLE
Limit diagonal speed in path planning 

### ISSUE THREAD

**Issue by Flova** [bit-bots/bitbots_main#366]
# Summary

Currently we can go full speed forwards and sideways at the same time. I think it would be reasonable to limit that based on the maximum forward/sideward movement. I don't know if a kite or ellipse shape for the maximum speed envelope would be suited best.

## Is your feature request related to a problem?

Sometimes steps seem unreasonably large when we go diagonally. I observed this on the real robot at the integration test.

## Describe the solution you'd like

Not only limit the movement speed along the x and y direction (while keeping the direction). We can also interpolate the max speed based on the angle.

## Describe alternatives you've considered

Lower the x and y speed. We accept slower speeds.

**Comment by texhnolyze** [comment]
@Flova Isn't this already done by these [lines](https://github.com/bit-bots/bitbots_main/blob/main/bitbots_navigation/bitbots_path_planning/bitbots_path_planning/controller.py#L126-L129)?
Can this issue be closed?

**Comment by Flova** [comment]
I think the current max speed envelope looks a bit like this:
![image](https://github.com/bit-bots/bitbots_main/assets/15075613/dd797672-d616-47c9-9d67-3a4c33968700)

The Idea was something like this:
![image](https://github.com/bit-bots/bitbots_main/assets/15075613/a37e6535-9e47-42ac-90a2-041820fc5695)

because we might not be able to walk with the same max vel diagonally than forward. But we need to chack that.
