### ISSUE TITLE
Deploy: Improve local main check formatting

### ISSUE THREAD

**Issue by jaagut** [bit-bots/bitbots_main#401]
# Summary
The confirmation prompt of the deploy tool could be improved by not showing the loading line.

## Expected behavior
No spinner and thus resetting line below the input prompt.

## Current behavior

![image](https://github.com/bit-bots/bitbots_main/assets/34797331/30f825e2-9481-485e-a153-ef6d70e3a836)

See image; we show a spinner line below the input prompt. This is irritating, as it suggests no input is needed and the line-reset also hides the user input.

**Comment by Flova** [comment]
Is this resolved by #413?

**Comment by jaagut** [comment]
Yes, thanks for the reminder
