### ISSUE TITLE
AttributeError: 'LocalizationBlackboard' object has no attribute 'last_state_pickup'

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_main#412]
# Summary
Error in localization handler when starting in simulation (`ros2 launch bitbots_bringup teamplayer_simulator.launch`). Probably, no default value is set in the blackboard constructor.

```
[localization_handler-28]   File "/home/timon/colcon_ws/build/dynamic_stack_decider/dynamic_stack_decider/dsd.py", line 285, in update
[localization_handler-28]     result = current_instance.perform()
[localization_handler-28]   File "/home/timon/colcon_ws/install/bitbots_localization_handler/share/bitbots_localization_handler/localization_dsd/decisions/pick_up.py", line 17, in perform
[localization_handler-28]     if self.blackboard.last_state_pickup:
[localization_handler-28] AttributeError: 'LocalizationBlackboard' object has no attribute 'last_state_pickup'
```

**Comment by Flova** [comment]
The might be related to outdated / not cleanbuild code. The line is not present: https://github.com/bit-bots/bitbots_main/blob/07589c040941a9614b205979d85f236b4bc46a42/bitbots_navigation/bitbots_localization_handler/bitbots_localization_handler/localization_dsd/decisions/pick_up.py#L12
