### ISSUE TITLE
robot_compile should have a watch mode

### ISSUE THREAD

**Issue by ftsell** [bit-bots/bitbots_main#44]
When run in _watch_ mode, robot_compile should watch targeted files and resync them if they change.
Of course in this mode, it would be non-terminated.

It would also be simpler to restrict ourselves to python files for now.

**Comment by jaagut** [comment]
This is not really a useful feature, as it necessitates continuous compilation, which takes lots of time. Also, one cannot be really sure what the compiled version on the robot is.
I cannot think of any situation, where this feature would have helped.
