### ISSUE TITLE
Turn stabilizer on in dynup

### ISSUE THREAD

**Issue by val-ba** [bit-bots/bitbots_main#467]
# Summary

Right now, as seen in the dynup_robot.yaml, the stabilizing is set to False.

## Describe the solution you'd like

I want it to be turned on and tested as it may not have been used in a while.
Additionally, the PIDs used only use values of 0 for p, i and d, but we have values in the config. So we might want to change these values in the dynup_stabilizer.cpp to the yaml values.

**Comment by Flova** [comment]
I don't think this is not needed right now. Stand up during the WorldCup worked mostly fine.
