### ISSUE TITLE
Technical Challenge Obstacle Avoidance

### ISSUE THREAD

**Issue by confusedlama** [bit-bots/bitbots_main#528]
# Summary
Our robots must be able to navigate to an arbitrary point on the other side of the playing field. While navigating the field the robot must avoid colored cylinders, while staying within a selected area. The rules for the technical challenge are specified in the [rules](http://humanoid.robocup.org/wp-content/uploads/RC-HL-2024-Rules.pdf) for the 2024 RoboCup. 

## Describe the solution you'd like
A vision that is able to detect cylinders of an arbitrary color with an arbitrary size is already implemented in this [directory](https://github.com/bit-bots/bitbots_main/tree/main/bitbots_misc/bitbots_technical_challenge_vision). The range of colors that are isolated can be tuned with dynamic reconfigure.

### general changes
- [x] rename [bitbots_technical_challenge_vision](https://github.com/bit-bots/bitbots_main/tree/main/bitbots_misc/bitbots_technical_challenge_vision) to bitbots_obstacle_avoidance_challenge and vision.launch to challenge.launch
- [x] make the planned path stay within the area the robot is allowed to walk (draw u in cost map for path planning)
- [x] add new map for technical challenge vision for localization with an additional line 1.5m to the right of the middle line 
### stuff that has to happen in this order to succeed at technical challenge 
- [x] start localization (using the obstacle avoidance field config), motion, path planning, technical challenge vision, vision
- [x] set localization to middle of the bottom side of the strip facing towards the goal position
- [x] listen to button2 short press
- [x] add goal pose behind the line of the other side of the playing field

## Tests
- [x] start path planning and check whether line looks right
- [x] have robot run to the other side of the field in *simulation* and check whether he is walking to the other side and stays roughly within the strip specified
- [x] do a test run with objects and a real robot

**Comment by Flova** [comment]
We didn't win the challenge, but we cleared the parkour. I think this is don't for now. Maybe we need a few adjustments for the next year, but we should make separate issues for that.
