### ISSUE TITLE
IMU Topic is not recorded

### ISSUE THREAD

**Issue by jgueldenstein** [bit-bots/bitbots_main#604]
# Summary
We use the wrong name for the IMU topic in https://github.com/bit-bots/bitbots_main/blob/8c5fb4e9f5d56d8f976b06dbafa891fa8e3cb4bf/bitbots_misc/bitbots_bringup/launch/rosbag_record.launch.py#L46

## Possible Solution
change topic to /imu/data as specified here: https://github.com/bit-bots/bitbots_main/blob/8c5fb4e9f5d56d8f976b06dbafa891fa8e3cb4bf/bitbots_lowlevel/bitbots_ros_control/config/wolfgang.yaml#L174

**Comment by Flova** [comment]
This is a disaster for the DDLITLAB project...
