### ISSUE TITLE
HCM dies because of not getting the wolfgang_hardware_interface parameters from other node

### ISSUE THREAD

**Issue by val-ba** [bit-bots/bitbots_main#637]
# Summary

In #2ee3299 the get_parameters from other node method was added. 
In #4037e548d703d0c84e56d84c9f04eb46c18e4fca the motor start delay was added.
Now the HCM dies, because a runtime error occurs when starting the sim script.
## Expected behavior

Normal simulator functionality with being able to walk etc.
## Current behavior

HCM dies.
There is not /wolfgang_hardware_interface node, because if sim is used the sim parameter is true.
This results in the ros_control.launch not being started which leads to the node in bitbots_ros_control not being started (no wolfgang_hardware_interface node).
## Steps to Reproduce

1. Build on current main.
2. Run ros2 launch bitbots_bringup simulator_teamplayer.launch game_controller:=false behavior:=false.
3. Wait 20 seconds.

## Possible Solution

- Use separate parameter for startup not in wolfgang.yaml.
- Set parameter in launch file
- Mock wolfgang_hardware_interface node for the parameters if sim:=true

**Comment by Flova** [comment]
Ah this is unfortunate, we don't wait the defined duration in the sim, but we still fetch the parameter in the blackboard...
